version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '09:00'
      timezone: 'America/Detroit'
    open-pull-requests-limit: 99
    reviewers:
      - 'warnellw'
